### ISSUE TITLE
Add support for Yaml

### ISSUE THREAD

**Issue by blavejr** [ZainChen/vscode-json#4]
Hey, would it be possible to add support for yaml files too?

**Comment by blavejr** [comment]
Hey, I tried to add yaml support but it starts to behave weird and I am not sure why because all I do it convert the yaml to json and than stringfy that json and pass it to json.parseTree
- The data is presented in the side bar, the keys are fine but the values are cut at what seem to be random places.
Do you perhaps have any idea why this is the case?

**Comment by klippx** [comment]
Remember that this is not the vscode-yaml extension, it is 100% about json. I would close this issue
